function stop_custom1
function stop_custom2
function stop_custom3
function stop_custom4
function stop_custom5
function stop_custom6
function stop_custom7
function stop_custom8
function stop_custom9
function stop_custom10
function stop_custom11
function stop_custom12
function stop_custom13
function stop_custom14
function stop_custom15
function stop_custom16